language: python

python:
  - 2.7

env:
  - DJANGO=1.6.0

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pyquery --use-mirrors
  - python setup.py -q install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
 - cd examples && ./manage.py test server
